module.exports = {
  Frontend: [
    "javascript",
    "react",
    "angular",
    "vue",
    "html",
    "css",
    "sass",
    "less",
    "bootstrap",
    "tailwindcss",
    "material-ui",
    "styled-components",
    "next.js",
    "gatsby",
    "nuxt.js",
    "svelte",
    "webassembly",
    "pwa",
    "webpack",
    "babel",
    "typescript",
    "jquery",
    "webgl",
    "three.js",
    "d3.js",
    "chart.js",
    "canvas",
    "svg",
    "web-components",
    "web-animations",
    "web-audio",
    "web",
  ],
  Backend: [
    "automation-sdk",
    "javascript",
    "node.js",
    "express",
    "flask",
    "django",
    "spring",
  ],
  DevOps: ["docker", "kubernetes", "CI/CD", "AWS", "GCP", "Azure"],
  Network: [
    "networking",
    "TCP/IP",
    "firewall",
    "router",
    "switch",
    "DNS",
    "DHCP",
    "network",
  ],
  Security: ["security", "encryption", "authentication"],

  "Artificial Intelligence": [
    "artificial intelligence",
    "AI",
    "computer vision",
    "image processing",
    "image recognition",
    "natural language processing",
    "NLP",
    "machine learning",
  ],
};
